export const sampleNFTJson = [
  {
    title: "Messi Legend",
    nftImageUrl: "https://lh3.googleusercontent.com/Fc9MM6INy2LvI_9kgvD_I03EXk_jo2sdcZn4EpX5PsmYCMm3QQYs7rlkt_Yim5CDMf_n0C_cFAmyDeCEB59w_yf_59kcucB0sAAJTZM=w600",
    offerTime: "12d 13h 56m",
    type: "digital",
    price: '90.00',
    currency : 'ETH',
    createdBy: "Shariq Shahzad",
    createdByAvatarUrl: "https://tl.vhv.rs/dpng/s/124-1246872_businessman-male-business-avatar-formal-man-natural-persons.png",
  },
  {
    title: "Barca",
    nftImageUrl: "https://lh3.googleusercontent.com/OKGs1CB7joMBAzox1__kay1_i_hCPowP9ArEVy0n6BreFRt78AkwTUdXwlx1XDA4_PhAWm_-fZUc1rCPwEX1vEI_-JSrIqR6UtmT=w306",
    offerTime: "11d 15h 26m",
    type: "phygital",
    price: '0.04',
    currency : 'ETH',
    createdBy: "Shariq Shahzad",
    createdByAvatarUrl: "https://tl.vhv.rs/dpng/s/124-1246872_businessman-male-business-avatar-formal-man-natural-persons.png",
  },
  {
    title: "Where my vans go",
    nftImageUrl: "https://lh3.googleusercontent.com/EZI4EKqiPis3jiYDf9V6igqyPXqvbzHr1tD5MNyS1q4GigeJ946qHl1lddKH0_iFbpNrNvuXQTjRcdG4hGBMyT9beTw2AtN8rI3HGQ=w306",
    offerTime: "12d 13h 01m",
    type: "phygital",
    price: '1.02',
    currency : 'ETH',
    createdBy: "Mohammed Ahmed",
    createdByAvatarUrl: "https://tl.vhv.rs/dpng/s/124-1246872_businessman-male-business-avatar-formal-man-natural-persons.png",
  },
  {
    title: "Party Bear",
    nftImageUrl: "https://lh3.googleusercontent.com/0Ti5EVGQCC3ESOhx3SmrGtiW38yNKhhTK_JS0TDGnkS_al2xLSbn3kVV4MIUpYe3y1WdwiXyXWvWdfvyJxnSbmAkIcrlL2EiB9CwIA=w306",
    offerTime: "17d 09h 50m",
    type: "phygital",
    price: '80.00',
    currency : 'ETH',
    createdBy: "Praveen Mangalampalli",
    createdByAvatarUrl: "https://tl.vhv.rs/dpng/s/124-1246872_businessman-male-business-avatar-formal-man-natural-persons.png",
  },
  {
    title: "Impostor",
    nftImageUrl: "https://lh3.googleusercontent.com/0D_d8huzQ7HE5prSNAPiNnMSa9DDYpx0nyZMV_RmYSwaWAy1ahsDbfshe6bvbmYhJnQRibtZAEqDjj1VWYXmE2JEpdbhfA8iVQTfcQ=w306",
    offerTime: "02d 03h 05m",
    type: "digital",
    price: '10.00',
    currency : 'ETH',
    createdBy: "Puneeta Akkina",
    createdByAvatarUrl: "https://www.vhv.rs/dpng/d/511-5119247_girl-male-and-female-avatar-hd-png-download.png",
  },
  {
    title: "Can you see us now",
    nftImageUrl: "https://lh3.googleusercontent.com/EZI4EKqiPis3jiYDf9V6igqyPXqvbzHr1tD5MNyS1q4GigeJ946qHl1lddKH0_iFbpNrNvuXQTjRcdG4hGBMyT9beTw2AtN8rI3HGQ=w306",
    offerTime: "18d 03h 53m",
    type: "digital",
    price: '20.00',
    currency : 'ETH',
    createdBy: "Affan Hasan",
    createdByAvatarUrl: "https://tl.vhv.rs/dpng/s/124-1246872_businessman-male-business-avatar-formal-man-natural-persons.png",
  },
  {
    title: "Cool Monkey",
    nftImageUrl: "https://lh3.googleusercontent.com/3-6AGCqSQVAPvMiCchD_x0YtxBvMlwPi5lY0Xn8cKO-D0_t6JHc5f7JRKdV-WM8OIA-Ib_B2EqHbqlJeqB9ZTL1BftaljKltZ2lNBg=w306",
    offerTime: "20d 03h 46m",
    type: "phygital",
    price: '40.00',
    currency : 'ETH',
    createdBy: "Affan Hasan",
    createdByAvatarUrl: "https://tl.vhv.rs/dpng/s/124-1246872_businessman-male-business-avatar-formal-man-natural-persons.png",
  },
  {
    title: "Laser Cat",
    nftImageUrl: "https://lh3.googleusercontent.com/DxIEzmmWEGjBvnwgKeJgdtI0VU_MGww4WADXA3VbPCojaSRJ1nSZnBi1luADNkPNmxBb5Nj0Ysxwm7YXkZyyXwU28zGaVCg_WOtvyHc=w306",
    offerTime: "15d 10h 36m",
    type: "digital",
    price: '30.00',
    currency : 'ETH',
    createdBy: "Mohammed Ahmed",
    createdByAvatarUrl: "https://tl.vhv.rs/dpng/s/124-1246872_businessman-male-business-avatar-formal-man-natural-persons.png",
  },
];
